# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


 ***Clase 4- Punto 1***

In [ ]:

import numpy as np
arreglo_de_ceros=np.zeros(

12)
print(arreglo_de_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


- [Documentacion NumPy](https://devdocs.io/numpy/)

***Punto 2 ***

In [ ]:


import numpy as np

posicion = np.zeros(10)
posicion[4] = 10
print(posicion)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


***Punto 3***

In [ ]:
import numpy as np

arreglo = np.arange(10, 50)
print(arreglo)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


***Punto 4***

In [ ]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8])
print(a)
a.shape=(3,3)
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


***Punto 5***

In [ ]:
import numpy as np

# Crear un arreglo de números aleatorios de longitud 100
aleatorio = np.random.rand(100)

# Calcular la media y la varianza del arreglo
MEDIA= np.mean(aleatorio)
VARIANZA = np.var(aleatorio)

print("Media:", MEDIA)
print("Varianza:", VARIANZA)


Media: 0.5397333336489525
Varianza: 0.07859238588308952


***Punto 6***

In [ ]:
import numpy as np


a = np.array([10, 15, 20, 45, 30])

# Calcula la media usando np.sum() y dividiendo por la longitud del arreglo
media = np.sum(arreglo) / len(arreglo)

print("Media:", media)


Media: 17.5


***Punto 7***

In [ ]:
import numpy as np

arreglo = np.array([5,10,15,5520,25,30])

# Calcular la media del arreglo
media = np.mean(arreglo)

# Calcular la diferencia al cuadrado entre cada elemento y la media
dif= (arreglo - media)


# Calcular la varianza sumando las diferencias al cuadrado y dividiendo por la longitud del arreglo
varianza = np.sum(dif) / len(arreglo)

print("Varianza:", varianza)


Varianza: -3.789561257387201e-14


***Punto 8***

In [ ]:
import numpy as np


aleatorio = np.random.randn(50)

print(aleatorio)


[ 0.28275205  0.69011373 -0.10474653 -0.40219406 -0.23306274  0.2842419
  1.06938367 -1.29001273 -0.19515654  0.04082195  1.81579144  0.71495361
  0.13490473 -0.72056416 -0.79071475  1.63313619 -1.3483101  -1.34974861
 -0.25332832 -1.79094165  0.42747063  1.30030281 -0.14338395  0.34993568
  0.84992356 -1.03862305 -0.00789188 -0.00653774 -0.41575266 -1.23475951
  1.44153138 -1.73516616 -0.71156433 -1.0200505   0.13966418  1.26018547
 -1.09266448 -0.33204026  1.19611842  1.07549233  0.54680849  0.05936659
  0.75786724  0.95294723  0.5815811   0.22373361 -0.21036531  0.00636843
 -0.93013785  0.90775489]
